# Generated by Django 5.1.7 on 2025-03-27 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='structures',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='is_active',
        ),
        migrations.AddField(
            model_name='structure',
            name='delegation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='document_management.delegation', verbose_name='Délégation'),
        ),
        migrations.AddField(
            model_name='structure',
            name='structure_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='document_management.structure', verbose_name='Structure parente'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='localisation',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='nom_delegation',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Nom de la délégation'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nom',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Nom'),
        ),
    ]
