# Generated by Django 5.1.7 on 2025-03-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0003_alter_structure_delegation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriedocument',
            name='code',
        ),
    ]
