# Generated by Django 5.1.7 on 2025-03-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0004_remove_categoriedocument_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
    ]
