# Generated by Django 5.1.7 on 2025-03-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0005_remove_role_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='role',
            name='date_modification',
        ),
    ]
