# Generated by Django 5.1.7 on 2025-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0006_remove_role_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-niveau'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AlterField(
            model_name='role',
            name='libelle',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('CONTROLLER', 'Contrôleur'), ('AGENT', 'Agent')], max_length=20, unique=True, verbose_name='Libellé'),
        ),
    ]
