name: Django CI/CD

on:
  push:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and tests
        working-directory: ./gestion_doc
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
          python manage.py test

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: llodia221/gestion-doc:latest

  # Optionnel : Test de déploiement complet avec Nginx
  integration-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create nginx config
        run: |
          mkdir -p nginx
          echo 'upstream django {
              server django-app:8000;
          }
          server {
              listen 80;
              location / {
                  proxy_pass http://django;
                  proxy_set_header Host $host;
              }
          }' > nginx.conf

      - name: Test deployment with docker-compose
        run: |
          docker-compose up -d
          sleep 30
          curl -f http://localhost || exit 1
          docker-compose down